### ISSUE TITLE
Apple Silicon Macs

### ISSUE THREAD

**Issue by billziss-gh** [ELIFE-ASU/PyInform#43]
Are there any plans to release this package and the associated inform library for Apple Silicon Macs?

```
Traceback (most recent call last):
  File "/Users/billziss/Projects/Fox-Tango/entropy/entropy.py", line 3, in <module>
    import pyinform as pi
  File "/Users/billziss/Projects/Fox-Tango/entropy/.venv/lib/python3.11/site-packages/pyinform/__init__.py", line 50, in <module>
    _inform = CDLL(get_libpath())
              ^^^^^^^^^^^^^^^^^^^
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ctypes/__init__.py", line 376, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: dlopen(/Users/billziss/Projects/Fox-Tango/entropy/.venv/lib/python3.11/site-packages/pyinform/inform-1.0.0/lib/macosx-x86_64/libinform.1.0.0.dylib, 0x0006): tried: '/Users/billziss/Projects/Fox-Tango/entropy/.venv/lib/python3.11/site-packages/pyinform/inform-1.0.0/lib/macosx-x86_64/libinform.1.0.0.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e' or 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/billziss/Projects/Fox-Tango/entropy/.venv/lib/python3.11/site-packages/pyinform/inform-1.0.0/lib/macosx-x86_64/libinform.1.0.0.dylib' (no such file), '/Users/billziss/Projects/Fox-Tango/entropy/.venv/lib/python3.11/site-packages/pyinform/inform-1.0.0/lib/macosx-x86_64/libinform.1.0.0.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e' or 'arm64'))
```

**Comment by andrepython** [comment]
Same issue, I tried to run pyinform with M4pro chip and get this error message (seems to have architecture incompatibility):
Traceback (most recent call last):
  File "/Users/andre/Library/CloudStorage/OneDrive-Personal/MOCHIALL/MOCHI/PROJECT/GEO/GEO10_ELSI/seismic_data_information_measurements/compare_info.py", line 7, in <module>
    import pyinform
  File "/Users/andre/Library/CloudStorage/OneDrive-Personal/MOCHIALL/MOCHI/PROJECT/GEO/GEO10_ELSI/seismic_data_information_measurements/elsi/lib/python3.9/site-packages/pyinform/__init__.py", line 50, in <module>
    _inform = CDLL(get_libpath())
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/ctypes/__init__.py", line 366, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(/Users/andre/Library/CloudStorage/OneDrive-Personal/MOCHIALL/MOCHI/PROJECT/GEO/GEO10_ELSI/seismic_data_information_measurements/elsi/lib/python3.9/site-packages/pyinform/inform-1.0.0/lib/macosx-x86_64/libinform.1.0.0.dylib, 0x0006): tried: '/Users/andre/Library/CloudStorage/OneDrive-Personal/MOCHIALL/MOCHI/PROJECT/GEO/GEO10_ELSI/seismic_data_information_measurements/elsi/lib/python3.9/site-packages/pyinform/inform-1.0.0/lib/macosx-x86_64/libinform.1.0.0.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e' or 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/andre/Library/CloudStorage/OneDrive-Personal/MOCHIALL/MOCHI/PROJECT/GEO/GEO10_ELSI/seismic_data_information_measurements/elsi/lib/python3.9/site-packages/pyinform/inform-1.0.0/lib/macosx-x86_64/libinform.1.0.0.dylib' (no such file), '/Users/andre/Library/CloudStorage/OneDrive-Personal/MOCHIALL/MOCHI/PROJECT/GEO/GEO10_ELSI/seismic_data_information_measurements/elsi/lib/python3.9/site-packages/pyinform/inform-1.0.0/lib/macosx-x86_64/libinform.1.0.0.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e' or 'arm64'))
